# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zPqUtwHJVhy-ZAxCY3FljLnfQn6SUOwS
"""


"""Ejercicio 1"""

mylist = list("abcdefghikjlmnopqrstuvwxyz")
ver=pd.DataFrame(mylist)
ver

"""Ejercicio 2"""

import numpy as np
ser1 = pd.Series(list("abcdefghijklmnopqrstuvwxyz"))
ser2 = pd.Series(np.arange(26))
ser = pd.DataFrame({"col1":ser1,"col2":ser2})
ser

"""Ejercicio 3"""

ser1 = pd.Series([1,2,3,4,5])
ser2 = pd.Series([4,5,6,7,8])
result = ser1.isin(ser2)
ser1[~result]

"""Ejercicio 4"""

ser = np.random.randint(1,10,35).reshape(7,5)
dataset = pd.DataFrame(ser)
dataset



"""Ejercicio 5"""

strig = ['how','to','kick','ass?']
ver = pd.DataFrame(strig)
ver

"""Ejercicio 6"""

p=pd.Series([1,2,3,4,5,6,7,8,9,10])
q=pd.Series([10,9,8,7,6,5,4,3,2,1])

p2=p.mul(p)
q2=q.mul(q)

suma=p2.add(q2)

final=np.sqrt(suma)
final2= pd.DataFrame(final)
final2

